# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30d0ddd071ee4fcce9c795042424e4fb83206eaae3e44bd1aa760a351c10eb6bd363a475cb15be9cd4ae735fb1b3970fc91e75ab51f8b64e84a4769d9d7e42f9

test:
  secret_key_base: a7c870fc9ccbee550d5916ee87b9bf9900aed493cce21e43612da3907bf08e17a217aa478983cda7b14ce2c5dfec6dd1979728be6449a4cd576d776629f56431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
